<table align="left" width=100%>
    <tr>
        <td width="10%">
            <img src="in_class.png">
        </td>
        <td>
            <div align="center">
                <font color="#21618C" size=8px>
                  <b> Inclass - Lab <br> (Day 1) </b>
                </font>
            </div>
        </td>
    </tr>
</table>

##  Table of Content

1. **[One Dimensional Array](#1D)**
2. **[Two Dimensional Array](#2D)**
3. **[Stacking](#Stacking)**
4. **[Splitting](#Splitting)**
5. **[For Loop](#loop)**

**Import the NumPy library before solving the exercises**

### Let's begin with some hands-on practice exercises

<a id="1D"> </a>
## 1. One Dimensional Array

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>1. Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below: (or create your own list)**<br>

    list_temperature = [3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68]

In [98]:
# type your code here
import numpy as np
list_temperature = [3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68]
list_temperature_array=np.array(list_temperature)
list_temperature_array

array([3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>2. Create a 1D array of weights of 10 students and retrieve all the weights greater than 68</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the weights given below: (or create your own list)**

    weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]

In [99]:

weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]
numpy_weights_array=np.array(weights)
numpy_weights_array[numpy_weights_array>68]

array([74.2, 85. , 74. , 70.5, 86. , 82. ])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>3. Write a code to generate 10 random integers between 20 to 40 (Is it possible to generate same random numbers everytime? If yes, describe the function)
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [ ]:
import numpy as np

np.random.seed(1)
numpy_random=np.random.randint(10,20,10)
numpy_random

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>4. Write a program to get the fifth power of the first five positive integers
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [121]:
first_five_numbers_fifth_power=[i**5 for i in range(1,6)]
print("first approach--",first_five_numbers_fifth_power)
#second approach is listed downside-----------------------------------------------
first_five_integers=np.arange(1,6)
print("second approach",first_five_integers**5)

first approach-- [1, 32, 243, 1024, 3125]
second approach [   1   32  243 1024 3125]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>5. Write a program to create an array of all the odd integers from 50 to 100 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [122]:
numpy_odd_array=np.array([i for i in range(50,101) if(i%2!=0)])
numpy_odd_array

array([51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83,
       85, 87, 89, 91, 93, 95, 97, 99])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>6. Write a program to calculate the sum of each column </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below: (or create your own array)**

    A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]

In [123]:
A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]
numpy_array_A=np.array(A)
numpy_array_A.sum(axis=0)

array([15, 25, 13])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>7. Write a code to get the element-wise remainder of an array after division by 8 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below:**<br>
    
    num = [42, 87, 90, 14, 32, 75, 61, 80, 92]

In [124]:
num = [42, 87, 90, 14, 32, 75, 61, 80, 92]
numpy_array_num=np.array(num)
numpy_array_num=numpy_array_num%8
numpy_array_num

array([2, 7, 2, 6, 0, 3, 5, 0, 4], dtype=int32)

<a id="2D"> </a>
## 2. Two Dimensional Array

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>8. Create a 2D numpy array from a 1D array of 20 elements of your choice. Further, subset the first 5 elements from the second element of a resulting 2D array 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [130]:
numpy_2d_array=np.arange(20).reshape(4,5)
numpy_2d_array
numpy_2d_array[1,:]


array([5, 6, 7, 8, 9])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>9. Write a program to find common values between two arrays 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below:**<br>

    prices_monday = [10, 30, 50, 60, 90]

    prices_tuesday = [50, 20, 80, 125, 10, 70]

In [134]:
prices_monday = [10, 30, 50, 60, 90]

prices_tuesday = [50, 20, 80, 125, 10, 70]
prices_monday_numpy_array=np.array(prices_monday)
prices_tuesday_numpy_array=np.array(prices_tuesday)
common_elements=np.intersect1d(prices_monday_numpy_array,prices_tuesday_numpy_array)

common_elements


array([10, 50])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>10. Write a program to find BMI of the patients whose height and weight is provided in the list given below 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below:**<br>

    list of weights (in kg)
    weights = [57, 69, 54, 65 ,71, 62, 56]

    list of heights (in m)<br>
    heights = [1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53] 

In [136]:
weights = [57, 69, 54, 65 ,71, 62, 56]
heights = [1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53] 
numpy_weights=np.array(weights)
numpy_heights=np.array(heights)
BMI=numpy_weights//(numpy_heights**2)
BMI

array([22., 22., 19., 21., 26., 20., 23.])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>11. Write a program to add a new column ([5,7]) at the last position in the array given below 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**

    array1 = [[[3, 4], [8, 2],[5, 9]]]

In [168]:
array1 = [[[3, 4], [8, 2],[5, 9]]]
numpy_array1=np.array(array1)
numpy_array2=np.insert(numpy_array1,-1,[5,7],axis=1)
numpy_array2

array([[[3, 4],
        [8, 2],
        [5, 7],
        [5, 9]]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>12. Write a code to print the identity matrix of order 5</b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [171]:
identity_matrix=np.identity(5)
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>13. Write a program to transpose a matrix 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the matrix given below:**
    
    M = [[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]]

In [172]:
M = [[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]]
array_M=np.array(M)
array_M.T

array([[15,  7, 54,  0],
       [17, 42,  3, 87],
       [45, 15, 61, 16],
       [56, 63, 41, 20]])

<a id="Stacking"> </a>
## 3. Stacking

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>14. Write a program to combine the two arrays vertically</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the arrays given below: (or create your own array)**<br>

    A1 = [[5, 9], [7, 6]]

    A2 = [[8,-7], [0,4]]

Combine the array A2 with A1

In [176]:
A1 = [[5, 9], [7, 6]]

A2 = [[8,-7], [0,4]]

numpy_array_A1=np.array(A1)
numpy_array_A2=np.array(A2)

numpy_array_A3=np.vstack((numpy_array_A2,numpy_array_A1))
numpy_array_A3

array([[ 8, -7],
       [ 0,  4],
       [ 5,  9],
       [ 7,  6]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>15. Write a code to combine the two arrays horizontally</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the arrays given below: (or create your own array)**

    A1 = [[-81, 75, 40], [27, 67, 52]]

    A2 = [[15, 54], [39, 56]]

Combine the array A2 with A1

In [177]:
A1 = [[-81, 75, 40], [27, 67, 52]]

A2 = [[15, 54], [39, 56]]

numpy_array_A1=np.array(A1)
numpy_array_A2=np.array(A2)

numpy_array_A3=np.hstack((numpy_array_A2,numpy_array_A1))
numpy_array_A3


array([[ 15,  54, -81,  75,  40],
       [ 39,  56,  27,  67,  52]])

<a id="Splitting"> </a>
## 4. Splitting

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>16. Write a code to divide the array into three sub-arrays containing
                       equal number of rows</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**<br>

    A = [[4, 7], [2, -3], [8, 1], [0, 9], [5,-1], [8, 3]]

In [180]:

A = [[4, 7], [2, -3], [8, 1], [0, 9], [5,-1], [8, 3]]
 
numpy_array_A=np.array(A)

numpy_array_vsplit=np.vsplit(numpy_array_A,3)
numpy_array_vsplit                             #vsplit along the rows

[array([[ 4,  7],
        [ 2, -3]]),
 array([[8, 1],
        [0, 9]]),
 array([[ 5, -1],
        [ 8,  3]])]

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>17. Write a program to divide the array into two sub-arrays containing equal number of columns
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**

    B = [[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1,3]]

In [181]:
B = [[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1,3]]
numpy_array_B=np.array(B)
numpy_array_hsplit=np.hsplit(numpy_array_B,2)
numpy_array_hsplit

[array([[ 8,  7],
        [ 2, -3],
        [ 8,  5]]),
 array([[ 0,  9],
        [ 5, 10],
        [-1,  3]])]

<a id="loop"> </a>
## 5. For Loop

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>18. Write a program to perform one-to-one mapping of the two lists</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below: (or create your own lists)**<br>

    L1 = [45, 67, 56, 71, 54, 62, 56]

    L2 = [21, 52, 64, 10, 49, 74, 26]

In [187]:
L1 = [45, 67, 56, 71, 54, 62, 56]

L2 = [21, 52, 64, 10, 49, 74, 26]

numpy_array_l1=np.array(L1)
numpy_array_l2=np.array(L2)

l3=[(i,j)  for i,j in zip(L1,L2)]
numpy_array_map=np.array(l3)
numpy_array_map


array([[45, 21],
       [67, 52],
       [56, 64],
       [71, 10],
       [54, 49],
       [62, 74],
       [56, 26]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>19. Define a for loop to apply the function (2x-1)/(x+5) on every element of an array </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below:**
    
    numbers = [6, 5, 3, 15]

In [218]:
new_lst=[]
def apply_func(x):
    global new_lst
    for i in range(len(x)):
        a=x[i]
        ans=(2*a-1)/(a+5)
        new_lst.append(ans)
        
        
   
 
numbers = [6, 5, 3, 15]
numpy_array_numbers=np.array(numbers)
np.apply_along_axis(apply_func,0,numpy_array_numbers)
np.array(new_lst)

array([1.   , 0.9  , 0.625, 1.45 ])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>20. Create an identity matrix with n dimensions (take input from the user). Fill the diagonals of that matrix with the multiples of the number provided by the user; take another input from the user. Consider the output below as an example </b>
                </font>
            </div>
        </td>
    </tr>
</table>

<table align="center">
    <td height = '100', width = '700'>
          <img src="que 20.png">
        </td>
</table>

In [258]:
n=int(input("enter the dimension"))
m=int(input("enter the multiple whose values u want to fill in diagonals"))

identity_matrix=np.identity(n)
count=1
for i in range(len(identity_matrix)):
    for j in range(len(identity_matrix[i])):
       
        if(i==j):
            
            identity_matrix[i][j]=m*(i+1)
            
        if(i+j==len(identity_matrix[i])-1):
            
            identity_matrix[i][j]=m*(j+1)
            
        
        
        
            
        
identity_matrix

enter the dimension8
enter the multiple whose values u want to fill in diagonals9


array([[ 9.,  0.,  0.,  0.,  0.,  0.,  0., 72.],
       [ 0., 18.,  0.,  0.,  0.,  0., 63.,  0.],
       [ 0.,  0., 27.,  0.,  0., 54.,  0.,  0.],
       [ 0.,  0.,  0., 36., 45.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 36., 45.,  0.,  0.,  0.],
       [ 0.,  0., 27.,  0.,  0., 54.,  0.,  0.],
       [ 0., 18.,  0.,  0.,  0.,  0., 63.,  0.],
       [ 9.,  0.,  0.,  0.,  0.,  0.,  0., 72.]])